details:
  namespace: student108-bookinfo-dev
  image: ghcr.io/bankhubjar/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.opsta.net
  path: "/student108/details(/|$)(.*)"
  serviceType: ClusterIP
